import React, { useEffect, useState } from 'react';
import { 
  UserPlus, Search, Trash2, CheckCircle, XCircle, Edit,
  ShieldCheck, Sparkles, Copy, Eye, EyeOff, Users, Key, CreditCard,
  FileSpreadsheet, Upload, Download, Filter
} from 'lucide-react';
import * as XLSX from 'xlsx';
import { 
  getUsersRequest, 
  createUserRequest, 
  updateUserRequest,
  toggleStatusRequest, 
  deleteUserRequest 
} from '../../services/user.service';

export const AdminUsuarios = () => {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('gestion'); // 'gestion' | 'excel'
  
  // Filtros
  const [searchTerm, setSearchTerm] = useState('');
  const [roleFilter, setRoleFilter] = useState('todos'); // 'todos' | 'admin' | 'atleta'

  // Modal manual
  const [showModal, setShowModal] = useState(false);
  const [editingUserId, setEditingUserId] = useState(null);
  const [showPassword, setShowPassword] = useState(false);
  const [copied, setCopied] = useState(false);

  // Campos del formulario manual
  const [rawNombre, setRawNombre] = useState('');
  const [rawApellido, setRawApellido] = useState('');
  const [carnet, setCarnet] = useState('');
  const [email, setEmail] = useState('');
  const [rol, setRol] = useState('atleta');

  // Estado de la carga de Excel
  const [excelData, setExcelData] = useState([]);
  const [excelFileName, setExcelFileName] = useState('');
  const [globalExcelRole, setGlobalExcelRole] = useState('atleta');
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);

  // Cargar lista de usuarios
  const loadUsers = async () => {
    try {
      setLoading(true);
      const data = await getUsersRequest();
      setUsers(data);
    } catch (err) {
      console.error("Error al cargar usuarios:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadUsers();
  }, []);

  // Lógica de generación automatizada de credenciales y correo
  const cleanNombre = rawNombre.trim().toLowerCase().replace(/\s+/g, '');
  const generatedUsername = cleanNombre && carnet ? `${cleanNombre}${carnet}` : '';
  const generatedPassword = carnet && cleanNombre ? `${carnet}${cleanNombre}*` : '';
  const autoGeneratedEmail = generatedUsername ? `${generatedUsername}@deporte.gob.bo` : '';

  useEffect(() => {
    if (!editingUserId && autoGeneratedEmail) {
      setEmail(autoGeneratedEmail);
    }
  }, [autoGeneratedEmail, editingUserId]);

  const openCreateModal = () => {
    resetForm();
    setEditingUserId(null);
    setShowModal(true);
  };

  const openEditModal = (user) => {
    setEditingUserId(user.id);
    setRawNombre(user.nombre || '');
    setRawApellido(user.apellido || '');
    setCarnet(user.ci || '');
    setEmail(user.email || '');
    setRol(user.rol || 'atleta');
    setShowPassword(false);
    setShowModal(true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!generatedUsername || !generatedPassword) {
      alert("Por favor ingresa un nombre y un carnet válidos para generar las credenciales.");
      return;
    }

    const payload = {
      nombre: rawNombre,
      apellido: rawApellido,
      ci: carnet,
      username: generatedUsername,
      email: email || `${generatedUsername}@deporte.gob.bo`,
      password: generatedPassword,
      rol: rol
    };

    try {
      if (editingUserId) {
        await updateUserRequest(editingUserId, payload);
      } else {
        await createUserRequest(payload);
      }
      setShowModal(false);
      resetForm();
      loadUsers();
    } catch (err) {
      alert(err.response?.data?.message || "Error al procesar la operación");
    }
  };

  const resetForm = () => {
    setRawNombre('');
    setRawApellido('');
    setCarnet('');
    setEmail('');
    setRol('atleta');
    setShowPassword(false);
    setEditingUserId(null);
  };

  const handleToggleStatus = async (id, currentStatus) => {
    try {
      await toggleStatusRequest(id, !currentStatus);
      loadUsers();
    } catch (err) {
      console.error("Error al cambiar estado:", err);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm("¿Estás seguro de que deseas eliminar este usuario?")) {
      try {
        await deleteUserRequest(id);
        loadUsers();
      } catch (err) {
        console.error("Error al eliminar usuario:", err);
      }
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // --- LÓGICA DE EXCEL CON SELECCIÓN DE ROL ---
  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setExcelFileName(file.name);
    const reader = new FileReader();

    reader.onload = (evt) => {
      const bstr = evt.target.result;
      const wb = XLSX.read(bstr, { type: 'binary' });
      const wsname = wb.SheetNames[0];
      const ws = wb.Sheets[wsname];
      const data = XLSX.utils.sheet_to_json(ws, { defval: "" });

      const parsed = data.map((row, index) => {
        const nom = (row.nombre || row.Nombre || '').toString().trim();
        const ape = (row.apellido || row.Apellido || '').toString().trim();
        const ci = (row.carnet || row.Carnet || row.ci || row.CI || '').toString().trim();

        const clean = nom.toLowerCase().replace(/\s+/g, '');
        const usr = clean && ci ? `${clean}${ci}` : `user${index + 1}`;
        const pass = ci && clean ? `${ci}${clean}*` : `123456*`;
        const mail = `${usr}@deporte.gob.bo`;

        return {
          idTemp: index + 1,
          nombre: nom,
          apellido: ape,
          ci: ci,
          username: usr,
          email: mail,
          password: pass,
          rol: globalExcelRole // Usa el rol por defecto seleccionado
        };
      });

      setExcelData(parsed);
    };

    reader.readAsBinaryString(file);
  };

  // Cambiar rol de forma global a todos los cargados en el Excel
  const handleGlobalRoleChange = (newRole) => {
    setGlobalExcelRole(newRole);
    setExcelData(prev => prev.map(item => ({ ...item, rol: newRole })));
  };

  // Cambiar rol de una sola fila individual
  const handleIndividualRoleChange = (idTemp, newRole) => {
    setExcelData(prev => prev.map(item => item.idTemp === idTemp ? { ...item, rol: newRole } : item));
  };

  const handleBatchImport = async () => {
    if (excelData.length === 0) return;
    setIsUploading(true);
    setUploadProgress(0);

    let successCount = 0;
    let failCount = 0;

    for (let i = 0; i < excelData.length; i++) {
      const item = excelData[i];
      try {
        await createUserRequest({
          nombre: item.nombre,
          apellido: item.apellido,
          ci: item.ci,
          username: item.username,
          email: item.email,
          password: item.password,
          rol: item.rol
        });
        successCount++;
      } catch (err) {
        console.error(`Error importando usuario ${item.username}:`, err);
        failCount++;
      }
      setUploadProgress(Math.round(((i + 1) / excelData.length) * 100));
    }

    setIsUploading(false);
    alert(`Proceso finalizado.\nCorrectos: ${successCount}\nFallidos: ${failCount}`);
    setExcelData([]);
    setExcelFileName('');
    setActiveTab('gestion');
    loadUsers();
  };

  const downloadExcelTemplate = () => {
    const templateData = [
      { nombre: 'Brian', apellido: 'Mamani', carnet: '4848' },
      { nombre: 'Carlos', apellido: 'Quispe', carnet: '1234' }
    ];
    const ws = XLSX.utils.json_to_sheet(templateData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Plantilla_Usuarios");
    XLSX.writeFile(wb, "Plantilla_Carga_Usuarios.xlsx");
  };

  // --- FILTRADO POR ROL (ADMIN / ATLETA) ---
  const filteredUsers = users.filter(user => {
    const term = searchTerm.toLowerCase();
    const username = user.username ? user.username.toLowerCase() : '';
    const userEmail = user.email ? user.email.toLowerCase() : '';
    const userCi = user.ci ? user.ci.toLowerCase() : '';
    const fullName = `${user.nombre || ''} ${user.apellido || ''}`.toLowerCase();
    
    const matchesSearch = username.includes(term) || userEmail.includes(term) || fullName.includes(term) || userCi.includes(term);

    if (roleFilter === 'admin') {
      return matchesSearch && user.rol === 'admin';
    } else if (roleFilter === 'atleta') {
      return matchesSearch && user.rol === 'atleta';
    }

    return matchesSearch;
  });

  const activeCount = users.filter(u => u.activo).length;
  const inactiveCount = users.length - activeCount;

  return (
    <div className="space-y-6 font-sans">
      
      {/* Encabezado */}
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 p-6 rounded-3xl text-white shadow-xl relative overflow-hidden">
        <div className="absolute -right-10 -bottom-10 w-40 h-40 bg-indigo-500/10 rounded-full blur-2xl pointer-events-none" />
        
        <div className="relative z-10">
          <div className="inline-flex items-center space-x-2 bg-indigo-500/20 text-indigo-300 text-xs font-semibold px-3 py-1 rounded-full mb-2 backdrop-blur-md">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Panel de Administración</span>
          </div>
          <h1 className="text-2xl font-extrabold tracking-tight">Gestión Integral de Usuarios</h1>
          <p className="text-xs text-slate-300 mt-1 max-w-xl">
            Crea cuentas individualmente o desde Excel asignando el rol antes de insertar.
          </p>
        </div>

        <div className="flex items-center space-x-2 relative z-10">
          <button 
            onClick={openCreateModal}
            className="inline-flex items-center justify-center space-x-2 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs py-2.5 px-4 rounded-xl shadow-lg shadow-indigo-600/30 transition-all active:scale-95"
          >
            <UserPlus className="w-4 h-4" />
            <span>Nuevo Manual</span>
          </button>
        </div>
      </header>

      {/* Pestañas de Navegación */}
      <div className="flex items-center space-x-2 border-b border-slate-200 pb-2">
        <button
          onClick={() => setActiveTab('gestion')}
          className={`flex items-center space-x-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${
            activeTab === 'gestion'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-500/20'
              : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
          }`}
        >
          <Users className="w-4 h-4" />
          <span>Lista de Usuarios</span>
        </button>

        <button
          onClick={() => setActiveTab('excel')}
          className={`flex items-center space-x-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${
            activeTab === 'excel'
              ? 'bg-emerald-600 text-white shadow-md shadow-emerald-500/20'
              : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
          }`}
        >
          <FileSpreadsheet className="w-4 h-4 text-emerald-500" />
          <span>Carga Masiva desde Excel</span>
        </button>
      </div>

      {/* PESTAÑA 1: LISTADO DE USUARIOS Y FILTROS */}
      {activeTab === 'gestion' && (
        <div className="space-y-6">
          {/* Métricas */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-white p-5 rounded-2xl border border-slate-200/80 shadow-sm flex items-center space-x-4">
              <div className="p-3 bg-blue-50 text-blue-600 rounded-xl">
                <Users className="w-6 h-6" />
              </div>
              <div>
                <p className="text-xs font-medium text-slate-400">Total Registrados</p>
                <p className="text-xl font-extrabold text-slate-800">{users.length}</p>
              </div>
            </div>

            <div className="bg-white p-5 rounded-2xl border border-slate-200/80 shadow-sm flex items-center space-x-4">
              <div className="p-3 bg-emerald-50 text-emerald-600 rounded-xl">
                <CheckCircle className="w-6 h-6" />
              </div>
              <div>
                <p className="text-xs font-medium text-slate-400">Activos</p>
                <p className="text-xl font-extrabold text-emerald-600">{activeCount}</p>
              </div>
            </div>

            <div className="bg-white p-5 rounded-2xl border border-slate-200/80 shadow-sm flex items-center space-x-4">
              <div className="p-3 bg-rose-50 text-rose-600 rounded-xl">
                <XCircle className="w-6 h-6" />
              </div>
              <div>
                <p className="text-xs font-medium text-slate-400">Deshabilitados</p>
                <p className="text-xl font-extrabold text-rose-600">{inactiveCount}</p>
              </div>
            </div>
          </div>

          {/* Buscador + Filtro por Rol (Admin vs Atleta) */}
          <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-sm flex flex-col sm:flex-row items-center justify-between gap-3">
            <div className="flex items-center space-x-3 w-full sm:w-auto flex-1">
              <Search className="w-5 h-5 text-slate-400" />
              <input 
                type="text" 
                placeholder="Buscar por usuario, carnet (CI), correo o nombre..." 
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full bg-transparent text-sm focus:outline-none text-slate-800 placeholder-slate-400"
              />
            </div>

            <div className="flex items-center space-x-2 w-full sm:w-auto pt-2 sm:pt-0 border-t sm:border-t-0 border-slate-100">
              <Filter className="w-4 h-4 text-slate-400" />
              <span className="text-xs text-slate-500 font-medium">Filtrar por Rol:</span>
              <select 
                value={roleFilter} 
                onChange={(e) => setRoleFilter(e.target.value)}
                className="bg-slate-50 border border-slate-200 text-xs font-bold text-slate-700 p-2 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
              >
                <option value="todos">Todos los Roles</option>
                <option value="admin">Solo Administradores</option>
                <option value="atleta">Solo Atletas</option>
              </select>
            </div>
          </div>

          {/* Tabla de Usuarios */}
          <div className="bg-white rounded-2xl border border-slate-200/80 shadow-sm overflow-hidden">
            {loading ? (
              <div className="p-12 text-center text-slate-500 text-sm flex flex-col items-center space-y-2">
                <div className="w-6 h-6 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin" />
                <span>Cargando usuarios...</span>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className="bg-slate-50/80 text-slate-500 font-bold uppercase tracking-wider border-b border-slate-100">
                    <tr>
                      <th className="py-4 px-6">Usuario / Persona</th>
                      <th className="py-4 px-6">CI (Carnet)</th>
                      <th className="py-4 px-6">Correo Auto-Generado</th>
                      <th className="py-4 px-6">Rol</th>
                      <th className="py-4 px-6">Estado</th>
                      <th className="py-4 px-6 text-right">Acciones</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 text-slate-700">
                    {filteredUsers.length === 0 ? (
                      <tr>
                        <td colSpan="6" className="py-8 text-center text-slate-400">
                          No se encontraron usuarios registrados.
                        </td>
                      </tr>
                    ) : (
                      filteredUsers.map((u) => {
                        const fullName = u.nombre || u.apellido ? `${u.nombre || ''} ${u.apellido || ''}`.trim() : u.username;
                        const initial = fullName.charAt(0).toUpperCase();

                        return (
                          <tr key={u.id} className="hover:bg-indigo-50/30 transition-colors group">
                            <td className="py-4 px-6">
                              <div className="flex items-center space-x-3">
                                <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-indigo-500 to-purple-600 text-white font-bold flex items-center justify-center text-sm shadow-sm group-hover:scale-105 transition-transform">
                                  {initial}
                                </div>
                                <div>
                                  <p className="font-bold text-slate-900 text-sm">{fullName}</p>
                                  <p className="text-[11px] text-indigo-600 font-medium">@{u.username}</p>
                                </div>
                              </div>
                            </td>

                            <td className="py-4 px-6 font-mono font-bold text-slate-700">
                              {u.ci ? (
                                <span className="inline-flex items-center space-x-1 bg-slate-100 px-2.5 py-1 rounded-lg border border-slate-200">
                                  <CreditCard className="w-3 h-3 text-slate-400" />
                                  <span>{u.ci}</span>
                                </span>
                              ) : (
                                <span className="text-slate-300 font-sans italic">Sin CI</span>
                              )}
                            </td>

                            <td className="py-4 px-6 font-medium text-slate-600">{u.email}</td>

                            <td className="py-4 px-6">
                              <span className={`inline-flex items-center px-2.5 py-1 rounded-lg text-[10px] font-extrabold uppercase tracking-wider ${
                                u.rol === 'admin' 
                                  ? 'bg-purple-100 text-purple-700 border border-purple-200' 
                                  : 'bg-slate-100 text-slate-700 border border-slate-200'
                              }`}>
                                {u.rol}
                              </span>
                            </td>

                            <td className="py-4 px-6">
                              <span className={`inline-flex items-center space-x-1.5 px-3 py-1 rounded-full text-[11px] font-semibold ${
                                u.activo 
                                  ? 'bg-emerald-50 text-emerald-700 border border-emerald-200/80' 
                                  : 'bg-rose-50 text-rose-700 border border-rose-200/80'
                              }`}>
                                <span className={`w-1.5 h-1.5 rounded-full ${u.activo ? 'bg-emerald-500' : 'bg-rose-500'}`} />
                                <span>{u.activo ? 'Activo' : 'Inactivo'}</span>
                              </span>
                            </td>

                            <td className="py-4 px-6 text-right space-x-1">
                              <button 
                                onClick={() => openEditModal(u)}
                                title="Editar usuario"
                                className="p-2 hover:bg-indigo-50 rounded-xl text-slate-400 hover:text-indigo-600 transition-colors"
                              >
                                <Edit className="w-4 h-4" />
                              </button>

                              <button 
                                onClick={() => handleToggleStatus(u.id, u.activo)}
                                title={u.activo ? 'Desactivar acceso' : 'Activar acceso'}
                                className="p-2 hover:bg-slate-100 rounded-xl text-slate-400 hover:text-slate-700 transition-colors"
                              >
                                {u.activo ? <XCircle className="w-4 h-4 text-amber-500" /> : <CheckCircle className="w-4 h-4 text-emerald-500" />}
                              </button>

                              <button 
                                onClick={() => handleDelete(u.id)}
                                title="Eliminar usuario"
                                className="p-2 hover:bg-rose-50 rounded-xl text-slate-400 hover:text-rose-600 transition-colors"
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </td>
                          </tr>
                        );
                      })
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}

      {/* PESTAÑA 2: CARGA MASIVA DESDE EXCEL Y SELECCIÓN DE ROL */}
      {activeTab === 'excel' && (
        <div className="bg-white p-6 rounded-3xl border border-slate-200/80 shadow-sm space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
            <div>
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center space-x-2">
                <FileSpreadsheet className="w-5 h-5 text-emerald-600" />
                <span>Importación Masiva desde Excel</span>
              </h2>
              <p className="text-xs text-slate-500 mt-0.5">
                Sube el archivo Excel con las columnas: <strong>nombre</strong>, <strong>apellido</strong> y <strong>carnet</strong>.
              </p>
            </div>

            <button 
              onClick={downloadExcelTemplate}
              className="inline-flex items-center space-x-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold text-xs py-2.5 px-4 rounded-xl transition-colors"
            >
              <Download className="w-4 h-4" />
              <span>Descargar Plantilla Demo</span>
            </button>
          </div>

          {/* Cargar Archivo */}
          <div className="border-2 border-dashed border-emerald-200 bg-emerald-50/30 rounded-2xl p-8 text-center space-y-3 relative">
            <input 
              type="file" 
              accept=".xlsx, .xls" 
              onChange={handleFileUpload}
              className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
            />
            <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-2xl flex items-center justify-center mx-auto">
              <Upload className="w-6 h-6" />
            </div>
            <div>
              <p className="text-sm font-bold text-slate-800">Haz clic o arrastra aquí tu archivo Excel</p>
              <p className="text-xs text-slate-400 mt-1">Soporta formatos .xlsx y .xls</p>
            </div>
            {excelFileName && (
              <span className="inline-block bg-emerald-600 text-white text-xs font-bold px-3 py-1 rounded-full">
                Archivo cargado: {excelFileName}
              </span>
            )}
          </div>

          {/* Previsualización y Asignación de Roles antes de subir */}
          {excelData.length > 0 && (
            <div className="space-y-4">
              <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-4">
                <div className="flex items-center space-x-3">
                  <span className="text-xs font-bold text-slate-700">Asignar Rol Global a Todos:</span>
                  <select 
                    value={globalExcelRole} 
                    onChange={(e) => handleGlobalRoleChange(e.target.value)}
                    className="bg-white border border-slate-300 font-extrabold text-xs text-indigo-700 py-2 px-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                  >
                    <option value="atleta">Atleta</option>
                    <option value="admin">Administrador</option>
                  </select>
                </div>

                <button
                  onClick={handleBatchImport}
                  disabled={isUploading}
                  className="inline-flex items-center space-x-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs py-2.5 px-6 rounded-xl shadow-lg shadow-emerald-600/30 transition-all active:scale-95 disabled:opacity-50"
                >
                  <span>Confirmar e Insertar Todo</span>
                </button>
              </div>

              {isUploading && (
                <div className="space-y-1">
                  <div className="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden">
                    <div 
                      className="bg-emerald-600 h-2.5 rounded-full transition-all duration-300"
                      style={{ width: `${uploadProgress}%` }}
                    />
                  </div>
                  <p className="text-right text-[11px] font-bold text-emerald-600">{uploadProgress}% completado</p>
                </div>
              )}

              <div className="overflow-x-auto max-h-80 overflow-y-auto rounded-2xl border border-slate-200">
                <table className="w-full text-left text-xs">
                  <thead className="bg-slate-50 text-slate-500 font-bold uppercase sticky top-0 border-b border-slate-200">
                    <tr>
                      <th className="py-3 px-4">#</th>
                      <th className="py-3 px-4">Nombre Completo</th>
                      <th className="py-3 px-4">CI (Carnet)</th>
                      <th className="py-3 px-4">Usuario Calculado</th>
                      <th className="py-3 px-4">Correo Auto-Generado</th>
                      <th className="py-3 px-4">Rol Asignado</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 text-slate-700">
                    {excelData.map((item) => (
                      <tr key={item.idTemp} className="hover:bg-slate-50">
                        <td className="py-3 px-4 font-bold text-slate-400">{item.idTemp}</td>
                        <td className="py-3 px-4 font-bold text-slate-800">{item.nombre} {item.apellido}</td>
                        <td className="py-3 px-4 font-mono">{item.ci}</td>
                        <td className="py-3 px-4 font-mono font-bold text-indigo-600">@{item.username}</td>
                        <td className="py-3 px-4 text-slate-500">{item.email}</td>
                        <td className="py-3 px-4">
                          <select 
                            value={item.rol}
                            onChange={(e) => handleIndividualRoleChange(item.idTemp, e.target.value)}
                            className="bg-white border border-slate-200 text-xs font-bold text-slate-800 p-1.5 rounded-lg focus:outline-none"
                          >
                            <option value="atleta">Atleta</option>
                            <option value="admin">Administrador</option>
                          </select>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Modal Manual */}
      {showModal && (
        <div className="fixed inset-0 bg-slate-950/60 backdrop-blur-sm flex items-center justify-center p-4 z-50 animate-fadeIn">
          <div className="bg-white rounded-3xl max-w-lg w-full p-6 shadow-2xl border border-slate-100 space-y-5 relative overflow-hidden">
            
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <div className="flex items-center space-x-2.5">
                <div className="p-2 bg-indigo-50 text-indigo-600 rounded-xl">
                  <Sparkles className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-base font-bold text-slate-900">
                    {editingUserId ? "Editar Usuario" : "Registrar Usuario Automatizado"}
                  </h2>
                  <p className="text-xs text-slate-400">Generación inteligente por Carnet (CI)</p>
                </div>
              </div>
              <button 
                onClick={() => setShowModal(false)}
                className="text-slate-400 hover:text-slate-600 p-1.5 rounded-lg hover:bg-slate-100"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleSubmit} className="space-y-4 text-xs">
              
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-semibold text-slate-700 mb-1">Nombre *</label>
                  <input 
                    type="text" 
                    required 
                    placeholder="Ej: Brian"
                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 text-slate-800" 
                    value={rawNombre} 
                    onChange={e => setRawNombre(e.target.value)} 
                  />
                </div>
                <div>
                  <label className="block font-semibold text-slate-700 mb-1">Apellido *</label>
                  <input 
                    type="text" 
                    required 
                    placeholder="Ej: Mamani"
                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 text-slate-800" 
                    value={rawApellido} 
                    onChange={e => setRawApellido(e.target.value)} 
                  />
                </div>
              </div>

              <div>
                <label className="block font-semibold text-slate-700 mb-1">Carnet de Identidad (CI) *</label>
                <input 
                  type="text" 
                  required 
                  placeholder="Ej: 4848"
                  className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 text-slate-800 font-mono" 
                  value={carnet} 
                  onChange={e => setCarnet(e.target.value)} 
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-semibold text-slate-700 mb-1">Correo Electrónico (Auto)</label>
                  <input 
                    type="email" 
                    required 
                    placeholder="Auto-generado"
                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 text-slate-800" 
                    value={email} 
                    onChange={e => setEmail(e.target.value)} 
                  />
                </div>
                <div>
                  <label className="block font-semibold text-slate-700 mb-1">Rol de Acceso</label>
                  <select 
                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 text-slate-800 font-semibold" 
                    value={rol} 
                    onChange={e => setRol(e.target.value)}
                  >
                    <option value="atleta">Atleta</option>
                    <option value="admin">Administrador</option>
                  </select>
                </div>
              </div>

              {/* Vista Previa de Credenciales Calculadas */}
              <div className="bg-indigo-50/60 border border-indigo-100 rounded-2xl p-4 space-y-2.5">
                <div className="flex items-center justify-between text-indigo-900 font-bold text-[11px]">
                  <span className="flex items-center space-x-1">
                    <Key className="w-3.5 h-3.5 text-indigo-600" />
                    <span>Credenciales Calculadas</span>
                  </span>
                  {generatedUsername && (
                    <button 
                      type="button" 
                      onClick={() => copyToClipboard(`Usuario: ${generatedUsername}\nPass: ${generatedPassword}`)}
                      className="text-indigo-600 hover:text-indigo-800 font-semibold flex items-center space-x-1"
                    >
                      <Copy className="w-3 h-3" />
                      <span>{copied ? '¡Copiado!' : 'Copiar'}</span>
                    </button>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-2 text-[11px]">
                  <div className="bg-white p-2 rounded-xl border border-indigo-100/80">
                    <span className="block text-slate-400 font-medium text-[10px]">Usuario:</span>
                    <span className="font-mono font-bold text-indigo-700">
                      {generatedUsername || <em className="text-slate-300 font-sans">Esperando datos...</em>}
                    </span>
                  </div>

                  <div className="bg-white p-2 rounded-xl border border-indigo-100/80 relative">
                    <span className="block text-slate-400 font-medium text-[10px]">Contraseña:</span>
                    <span className="font-mono font-bold text-slate-800 block truncate pr-5">
                      {generatedPassword ? (
                        showPassword ? generatedPassword : '••••••••••'
                      ) : (
                        <em className="text-slate-300 font-sans">Esperando datos...</em>
                      )}
                    </span>
                    {generatedPassword && (
                      <button 
                        type="button" 
                        onClick={() => setShowPassword(!showPassword)}
                        className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                      >
                        {showPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                      </button>
                    )}
                  </div>
                </div>
              </div>

              <div className="flex justify-end space-x-2 pt-2">
                <button 
                  type="button" 
                  onClick={() => setShowModal(false)} 
                  className="px-4 py-2.5 border border-slate-200 rounded-xl text-slate-600 hover:bg-slate-50 font-semibold transition-colors"
                >
                  Cancelar
                </button>
                <button 
                  type="submit" 
                  disabled={!generatedUsername || !generatedPassword}
                  className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white rounded-xl font-semibold shadow-md shadow-indigo-500/20 transition-all active:scale-95"
                >
                  {editingUserId ? "Actualizar Usuario" : "Crear Usuario"}
                </button>
              </div>

            </form>
          </div>
        </div>
      )}

    </div>
  );
};